include: package:lints/recommended.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - lib/src/model/network/*
    - lib/src/model/network/*.g.dart
    - lib/src/model/network/*.freezed.dart
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    - always_declare_return_types
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - one_member_abstracts
    - only_throw_errors
    - package_api_docs
    - prefer_single_quotes
    - sort_child_properties_last
    - provide_deprecation_message
    - prefer_mixin
    - prefer_null_aware_operators
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_if_null_operators
    - prefer_const_declarations
    - prefer_const_constructors_in_immutables
